import styles from "./TermsPrivacy.module.css";
import { Link } from "react-router-dom";

function Body() {
    return (
        <div className={styles.body_overlay}>
            <div className={styles.body}>
                <h1>Privacy Policy</h1>

                <p>Effective date: 2022-10-23</p>

                <h2>Introduction</h2>
                <p>Welcome to <b>Tmlab</b>.<br />
                    <b>Tmlab</b> (“us”, “we”, or “our”) operates <b>tmlab.tech</b>(hereinafter referred to as <b>“Service”</b>).<br />
                    Our Privacy Policy governs your visit to <b>tmlab.tech</b>, and explains how we collect, safeguard and disclose information that results from your use of our Service. <br />
                    We use your data to provide and improve Service. By using Service, you agree to the collection and use of information in accordance with this policy. Unless otherwise defined in this Privacy Policy, the terms used in this Privacy Policy have the same meanings as in our <Link to='/terms'>Terms of service</Link><br />
                    Our <Link to='/terms'>Terms of Service</Link> (<b>“Terms”</b>) govern all use of our Service and together with the Privacy Policy constitutes your agreement with us (<b>“agreement”</b>).
                </p>

                <h2>Definitions</h2>
                <p>
                    <b>SERVICE</b> means the <b>tmlab.tech</b> website operated by Tmlab.
                </p>
                <p>
                    <b>PERSONAL DATA</b> means data about a living individual who can be identified from those data (or from those and other information either in our possession or likely to come into our possession).
                </p>
                <p>
                    <b>USAGE DATA</b> is data collected automatically either generated by the use of Service or from Service infrastructure itself (for example, the duration of a page visit).
                </p>
                <p>
                    <b>COOKIES</b> are small files stored on your device (computer or mobile device).
                </p>
                <p>
                    <b>DATA CONTROLLER</b> means a natural or legal person who (either alone or jointly or in common with other persons) determines the purposes for which and the manner in which any personal data are, or are to be, processed. For the purpose of this Privacy Policy, we are a Data Controller of your data.
                </p>
                <p>
                    <b>DATA PROCESSORS (OR SERVICE PROVIDERS)</b> means any natural or legal person who processes the data on behalf of the Data Controller. We may use the services of various Service Providers in order to process your data more effectively.
                </p>
                <p>
                    <b>DATA SUBJECT</b> is any living individual who is the subject of Personal Data.
                </p>
                <p>
                    <b>THE USER</b> is the individual using our Service. The User corresponds to the Data Subject, who is the subject of Personal Data.
                </p>

                <h2>Information Collection and Use</h2>
                <p>
                    We collect several different types of information for various purposes to provide and improve our Service to you.
                </p>

                <h2>Types of Data Collected</h2>

                <h3>Personal Data</h3>
                <p>
                    While using our Service, we may ask you to provide us with certain personally identifiable information that can be used to contact or identify you (<b>“Personal Data”</b>). Personally identifiable information may include, but is not limited to:
                </p>
                <ul>
                    <li>Email address</li>
                    <li>First name and last name</li>
                </ul>
                <p>
                    We may use your Personal Data to contact you with newsletters, marketing or promotional materials and other information that may be of interest to you. You may opt out of receiving any, or all, of these communications from us by following the unsubscribe link.
                </p>

                <h3>Usage Data</h3>
                <p>
                    We may also collect information that your browser sends whenever you visit our Service or when you access Service by or through any device (<b>“Usage Data”</b>).
                </p>
                <p>
                    This Usage Data may include information such as your computer's Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that you visit, the time and date of your visit, the time spent on those pages, unique device identifiers and other diagnostic data.
                </p>
                <p>
                    When you access Service with a device, this Usage Data may include information such as the type of device you use, your device unique ID, the IP address of your device, your device operating system, the type of Internet browser you use, unique device identifiers and other diagnostic data.
                </p>

                <h2>Use of Data</h2>
                <p>Tmlab uses the collected data for various purposes:</p>
                <ul>
                    <li>To provide and maintain our Service.</li>
                    <li>To notify you about changes to our Service.</li>
                    <li>To provide customer support.</li>
                    <li>
                        To gather analysis or valuable information so that we can improve our Service.
                    </li>
                    <li>To monitor the usage of our Service.</li>
                    <li>To detect, prevent and address technical issues.</li>
                    <li>To fulfil any other purpose for which you provide it.</li>
                    <li>
                        To carry out our obligations and enforce our rights arising from any contracts entered into between you and us, including for billing and collection.
                    </li>
                    <li>
                        To provide you with news, special offers and general information about other goods, services and events which we offer that are similar to those that you have already purchased or enquired about unless you have opted not to receive such information.
                    </li>
                    <li>
                        In any other way we may describe when you provide the information.
                    </li>
                    <li>For any other purpose with your consent.</li>
                </ul>

                <h2>Retention of Data</h2>
                <p>
                    We will retain your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use your Personal Data to the extent necessary to comply with our legal obligations (for example, if we are required to retain your data to comply with applicable laws), resolve disputes, and enforce our legal agreements and policies.
                </p>
                <p>
                    We will also retain Usage Data for internal analysis purposes. Usage Data is generally retained for a shorter period, except when this data is used to strengthen the security or to improve the functionality of our Service, or we are legally obligated to retain this data for longer time periods.
                </p>

                <h2>Transfer of Data</h2>
                <p>
                    Your information, including Personal Data, may be transferred to and maintained on computers located outside of your state, province, country or other governmental jurisdiction where the data protection laws may differ from those of your jurisdiction.</p>
                <p>
                    If you are located outside South Africa and choose to provide information to us, please note that we transfer the data, including Personal Data, to South Africa and process it there.
                </p>
                <p>
                    Your consent to this Privacy Policy followed by your submission of such information represents your agreement to that transfer.
                </p>
                <p>
                    Tmlab will take all the steps reasonably necessary to ensure that your data is treated securely and in accordance with this Privacy Policy and no transfer of your Personal Data will take place to an organisation or a country unless there are adequate controls in place including the security of your data and other personal information.
                </p>

                <h2>Security of Data</h2>
                <p>
                    The security of your data is important to us but remember that no method of transmission over the Internet or method of electronic storage is 100% secure. We strive to use commercially acceptable means to protect your Personal Data.
                </p>

                <h2>
                    Your Data Protection Rights Under General Data Protection Regulation (GDPR)
                </h2>
                <p>
                    If you are a resident of the European Union (EU) and European Economic Area (EEA), you have certain data protection rights, covered by GDPR.
                </p>
                <p>
                    We aim to take reasonable steps to allow you to correct, amend, delete, or limit the use of your Personal Data.
                </p>
                <p>
                    If you wish to be informed what Personal Data we hold about you and if you want it to be removed from our systems, please email us at <a href="mailto:support@tmlab.tech">support@tmlab.tech</a>.
                </p>
                <p>
                    In certain circumstances, you have the following data protection rights:
                </p>
                <ul>
                    <li>
                        The right to access, update or to delete the information we have on you.
                    </li>
                    <li>
                        The right of rectification. You have the right to have your information rectified if that information is inaccurate or incomplete.
                    </li>
                    <li>
                        The right to object. You have the right to object to our processing of your Personal Data.
                    </li>
                    <li>
                        The right of restriction. You have the right to request that we restrict the processing of your personal information.
                    </li>
                    <li>
                        The right to data portability. You have the right to be provided with a copy of your Personal Data in a structured, machine-readable and commonly used format.
                    </li>
                    <li>
                        The right to withdraw consent. You also have the right to withdraw your consent at any time where we rely on your consent to process your personal information.
                    </li>
                    <li>
                        Please note that we may ask you to verify your identity before responding to such requests. Please note, we may not able to provide Service without some necessary data.
                    </li>
                    <li>
                        You have the right to complain to a Data Protection Authority about our collection and use of your Personal Data. For more information, please contact your local data protection authority in the European Economic Area (EEA).
                    </li>
                </ul>

                <h2>
                    Your Data Protection Rights under the California Privacy Protection Act (CalOPPA)
                </h2>
                <p>
                    CalOPPA is the first state law in the nation to require commercial websites and online services to post a privacy policy. The law's reach stretches well beyond California to require a person or company in the United States (and conceivable the world) that operates websites collecting personally identifiable information from California consumers to post a conspicuous privacy policy on its website stating exactly the information being collected and those individuals with whom it is being shared, and to comply with this policy.
                </p>
                <p>According to CalOPPA we agree to the following:</p>
                <ul>
                    <li>Users can visit our site anonymously.</li>
                    <li>
                        Our Privacy Policy link includes the word “Privacy”, and can easily be found on the home page of our website.
                    </li>
                    <li>
                        Users will be notified of any privacy policy changes on our Privacy Policy Page.
                    </li>
                    <li>
                        Users are able to change their personal information by emailing us at <a href="mailto:support@tmlab.tech">support@tmlab.tech</a>
                    </li>
                    <li>Our Policy on “Do Not Track” Signals:</li>
                    <li>
                        We honor Do Not Track signals and do not track, plant cookies, or use advertising when a Do Not Track browser mechanism is in place. Do Not Track is a preference you can set in your web browser to inform websites that you do not want to be tracked.
                    </li>
                </ul>

                <h2>
                    Your Data Protection Rights under the California Consumer Privacy Act (CCPA)
                </h2>
                <p>
                    If you are a California resident, you are entitled to learn what data we collect about you, ask to delete your data and not to sell (share) it. To exercise your data protection rights, you can make certain requests and ask us:
                </p>
                <ul>
                    <li>
                        What personal information we have about you. If you make this request, we will return to you the categories of personal information we have collected about you.Please note, you are entitled to ask us to provide you with this information up to two times in a rolling twelve-month period. When you make this request, the information provided may be limited to the personal information we collected about you in the previous 12 months.

                    </li>
                    <li>
                        To delete your personal information. If you make this request, we will delete the personal information we hold about you as of the date of your request from our records and direct any service providers to do the same. In some cases, deletion may be accomplished through de-identification of the information. If you choose to delete your personal information, you may not be able to use certain functions that require your personal information to operate.
                    </li>
                    <li>
                        To stop selling your personal information. We don't sell or rent your personal information to any third parties for any purpose. We do not sell your personal information for monetary consideration. However, under some circumstances, a transfer of personal information to a third party, or within our family of companies, without monetary consideration may be considered a “sale” under California law. You are the only owner of your Personal Data and can request disclosure or deletion at any time.

                    </li>
                </ul>
                <p>
                    To exercise your California data protection rights described above, please send your request(s) by email: <a href="mailto:support@tmlab.tech">support@tmlab.tech</a><br />
                    Your data protection rights, described above, are covered by the CCPA, short for the California Consumer Privacy Act. To find out more, visit the official California Legislative Information website. The CCPA took effect on 01/01/2020.
                </p>

                <h2>Links to Other Sites</h2>
                <p>
                    Our Service may contain links to other sites that are not operated by us. If you click a third party link, you will be directed to that third party's site. We strongly advise you to review the Privacy Policy of every site you visit.
                </p>
                <p>
                    We have no control over and assume no responsibility for the content, privacy policies or practices of any third party sites or services.
                </p>

                <h2>Childrens's Privacy</h2>
                <p>
                    Our Services are not intended for use by children under the age of 18 (<b>“Child”</b> or <b>“Children”</b>).
                </p>
                <p>
                    We do not knowingly collect personally identifiable information from Children under 18. If you become aware that a Child has provided us with Personal Data, please contact us. If we become aware that we have collected Personal Data from Children without verification of parental consent, we take steps to remove that information from our servers.
                </p>

                <h2>Changes to This Privacy Policy</h2>
                <p>
                    We may update our Privacy Policy from time to time. We will notify you of any changes by posting the new Privacy Policy on this page.<br />
                    We will let you know via email and/or a prominent notice on our Service, prior to the change becoming effective and update “effective date” at the top of this Privacy Policy.<br />
                    You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when they are posted on this page.
                </p>
            </div>
        </div>
    );
}

export default Body;